// SPDX-License-Identifier: GPL-3.0-or-later
//! Checked against the reference implementation, not against prose.
//!
//! `contract/rencode-corpus.json` is generated by `tools/gen_rencode_corpus.py`
//! running the real Python rencode. Every case pins a boundary in the format or
//! reproduces a message Deluge actually sends. Both directions are checked: our
//! encoder must produce Python's bytes, and our decoder must produce Python's
//! values.

use redeluge_rencode::{from_slice, to_vec, StringMode, Value};
use serde_json::Value as Json;

const CORPUS: &str = include_str!("../../../contract/rencode-corpus.json");

struct Case {
    description: String,
    value: Value,
    encoded: Vec<u8>,
    decoded_utf8: Option<Value>,
    decoded_raw: Value,
}

fn corpus() -> Vec<Case> {
    let parsed: Json = serde_json::from_str(CORPUS).expect("corpus is not valid JSON");
    parsed["cases"]
        .as_array()
        .expect("corpus has no cases")
        .iter()
        .map(|case| Case {
            description: case["description"].as_str().unwrap().to_owned(),
            value: described(&case["value"]),
            encoded: hex(case["encoded"].as_str().unwrap()),
            decoded_utf8: (!case["decoded_utf8"].is_null())
                .then(|| described(&case["decoded_utf8"])),
            decoded_raw: described(&case["decoded_raw"]),
        })
        .collect()
}

/// Turns the corpus's typed JSON back into a [`Value`].
fn described(json: &Json) -> Value {
    match json["t"].as_str().expect("case has no type tag") {
        "none" => Value::None,
        "bool" => Value::Bool(json["v"].as_bool().unwrap()),
        "int" => {
            let text = json["v"].as_str().unwrap();
            match text.parse::<i64>() {
                Ok(number) => Value::Int(number),
                Err(_) => Value::BigInt(text.to_owned()),
            }
        }
        // The corpus stores Python's repr of the double that came out of a
        // float32, so it is exactly representable as f32.
        "f32" => Value::Float32(json["v"].as_str().unwrap().parse::<f64>().unwrap() as f32),
        "f64" => Value::Float64(json["v"].as_str().unwrap().parse().unwrap()),
        "bytes" => Value::Bytes(hex(json["v"].as_str().unwrap())),
        "str" => Value::Str(json["v"].as_str().unwrap().to_owned()),
        "list" => Value::List(
            json["v"]
                .as_array()
                .unwrap()
                .iter()
                .map(described)
                .collect(),
        ),
        "dict" => Value::Dict(
            json["v"]
                .as_array()
                .unwrap()
                .iter()
                .map(|pair| (described(&pair[0]), described(&pair[1])))
                .collect(),
        ),
        other => panic!("corpus uses an unknown type tag: {other}"),
    }
}

fn hex(text: &str) -> Vec<u8> {
    (0..text.len())
        .step_by(2)
        .map(|index| u8::from_str_radix(&text[index..index + 2], 16).expect("bad hex"))
        .collect()
}

/// Compares floats by bit pattern, so -0.0 and 0.0 stay distinct.
fn same(left: &Value, right: &Value) -> bool {
    match (left, right) {
        (Value::Float32(a), Value::Float32(b)) => a.to_bits() == b.to_bits(),
        (Value::Float64(a), Value::Float64(b)) => a.to_bits() == b.to_bits(),
        (Value::List(a), Value::List(b)) => {
            a.len() == b.len() && a.iter().zip(b).all(|(x, y)| same(x, y))
        }
        (Value::Dict(a), Value::Dict(b)) => {
            a.len() == b.len()
                && a.iter()
                    .zip(b)
                    .all(|((ak, av), (bk, bv))| same(ak, bk) && same(av, bv))
        }
        _ => left == right,
    }
}

#[test]
fn the_corpus_is_not_empty() {
    let cases = corpus();
    assert!(
        cases.len() >= 70,
        "the corpus lost cases: {} remain",
        cases.len()
    );
}

#[test]
fn we_encode_exactly_what_python_encodes() {
    for case in corpus() {
        let ours = to_vec(&case.value);
        assert_eq!(
            ours, case.encoded,
            "encoding diverged for `{}`\n  ours:   {:02x?}\n  python: {:02x?}",
            case.description, ours, case.encoded
        );
    }
}

#[test]
fn we_decode_exactly_what_python_decodes_in_utf8_mode() {
    for case in corpus() {
        let Some(expected) = case.decoded_utf8 else {
            continue; // Python refuses this one; covered separately below.
        };
        let ours = from_slice(&case.encoded, StringMode::Utf8Lossy)
            .unwrap_or_else(|err| panic!("failed to decode `{}`: {err}", case.description));
        assert!(
            same(&ours, &expected),
            "decoding diverged for `{}`\n  ours:   {ours:?}\n  python: {expected:?}",
            case.description
        );
    }
}

#[test]
fn we_decode_exactly_what_python_decodes_in_raw_mode() {
    for case in corpus() {
        let ours = from_slice(&case.encoded, StringMode::Raw)
            .unwrap_or_else(|err| panic!("failed to decode `{}`: {err}", case.description));
        assert!(
            same(&ours, &case.decoded_raw),
            "raw decoding diverged for `{}`\n  ours:   {ours:?}\n  python: {:?}",
            case.description,
            case.decoded_raw
        );
    }
}

#[test]
fn we_keep_bytes_that_python_refuses_to_decode() {
    // The one deliberate divergence. Python raises UnicodeDecodeError on a
    // string that is not valid UTF-8 when decode_utf8 is on, and a peer
    // controls torrent names, so that is reachable from the network. We keep
    // the raw bytes and carry on.
    let refused: Vec<Case> = corpus()
        .into_iter()
        .filter(|case| case.decoded_utf8.is_none())
        .collect();

    assert!(
        !refused.is_empty(),
        "the corpus no longer covers invalid UTF-8"
    );

    for case in refused {
        let ours = from_slice(&case.encoded, StringMode::Utf8Lossy).unwrap_or_else(|err| {
            panic!(
                "`{}` must decode to bytes, not fail: {err}",
                case.description
            )
        });
        assert!(
            same(&ours, &case.decoded_raw),
            "`{}` should fall back to exactly the raw bytes",
            case.description
        );
    }
}

#[test]
fn every_case_survives_our_own_round_trip() {
    for case in corpus() {
        let encoded = to_vec(&case.value);
        let decoded = from_slice(&encoded, StringMode::Raw)
            .unwrap_or_else(|err| panic!("round trip failed for `{}`: {err}", case.description));
        let re_encoded = to_vec(&decoded);
        assert_eq!(
            encoded, re_encoded,
            "`{}` does not re-encode to the same bytes",
            case.description
        );
    }
}

#[test]
fn encoding_is_canonical() {
    // Each value has exactly one encoding, so decoding then re-encoding any
    // corpus entry reproduces the original bytes. Without this the daemon and
    // the web server could disagree about a message they both consider valid.
    for case in corpus() {
        let decoded = from_slice(&case.encoded, StringMode::Raw).unwrap();
        assert_eq!(
            to_vec(&decoded),
            case.encoded,
            "`{}` has more than one encoding",
            case.description
        );
    }
}
