[package]
name = "redeluge-rencode"
description = "The rencode wire format used by the Deluge RPC protocol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
thiserror.workspace = true

[dev-dependencies]
serde.workspace = true
serde_json.workspace = true
